"""
P2 three-in-one update to index.html:
1. Export Prompt as Image - canvas API, download PNG
2. AI Model Test - user enters API key, call StepFun/OpenAI API directly
3. Chrome extension files created separately
"""
import re

with open(r'D:\jieyuexingchen\promptblocks\index.html', 'r', encoding='utf-8') as f:
    content = f.read()

changes = 0

# ========== P2-1: Export as Image ==========

# 1a. Add export button after save button
old_save_end = '<span data-i18n="save">保存</span>\n      </button>'
new_buttons = old_save_end + '\n      <button class="btn btn-secondary" id="exportBtn" onclick="exportImage()" style="padding:10px 14px">\n        <span>🖼️</span> <span data-i18n="exportImg">导出图片</span>\n      </button>\n      <button class="btn btn-secondary" id="testBtn" onclick="toggleTestPanel()" style="padding:10px 14px">\n        <span>🧪</span> <span data-i18n="testAI">测试效果</span>\n      </button>'
if old_save_end in content:
    content = content.replace(old_save_end, new_buttons, 1)
    changes += 1
    print('1a. Export + Test buttons added')
else:
    print('1a. save_end not found')

# 1b. Add i18n keys
content = content.replace("history: '历史记录',", "history: '历史记录', exportImg: '导出图片', testAI: '测试效果',", 1)
content = content.replace("history: 'History',", "history: 'History', exportImg: 'Export Image', testAI: 'Test AI',", 1)
changes += 2
print('1b. i18n keys added')

# 1c. Add export image JS + test panel JS
p2_js = '''
// ===== P2-1: Export Prompt as Image =====
function exportImage() {
  var text = document.getElementById('promptPreview').textContent;
  if (!text || text.trim() === '') { showToast('拼装区为空'); return; }

  var isLight = document.documentElement.getAttribute('data-theme') === 'light';
  var bg = isLight ? '#ffffff' : '#1a1a2e';
  var fg = isLight ? '#1a1a2e' : '#e0e0e8';
  var accent = '#6366f1';
  var mutedColor = isLight ? '#6b7280' : '#8888a0';

  // Split text into lines for wrapping
  var maxWidth = 680;
  var lineHeight = 26;
  var fontSize = 14;
  var padding = 40;
  var headerHeight = 80;
  var footerHeight = 50;

  // Create a temp canvas to measure text
  var tc = document.createElement('canvas');
  var tctx = tc.getContext('2d');
  tctx.font = fontSize + 'px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

  // Word wrap
  var paragraphs = text.split('\\n');
  var lines = [];
  paragraphs.forEach(function(para) {
    if (para.trim() === '') { lines.push(''); return; }
    var words = para.split('');
    var current = '';
    for (var i = 0; i < words.length; i++) {
      var test = current + words[i];
      if (tctx.measureText(test).width > maxWidth && current) {
        lines.push(current);
        current = words[i];
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
  });

  var totalLines = lines.length;
  var contentHeight = totalLines * lineHeight + 40;
  var totalHeight = headerHeight + contentHeight + footerHeight;

  var canvas = document.createElement('canvas');
  canvas.width = 760;
  canvas.height = totalHeight;
  var ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  // Header bar
  var grad = ctx.createLinearGradient(0, 0, canvas.width, 0);
  grad.addColorStop(0, '#6366f1');
  grad.addColorStop(1, '#ec4899');
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, canvas.width, 6);

  // Header text
  ctx.fillStyle = accent;
  ctx.font = 'bold 20px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  ctx.fillText('\\u{1F9F1} PromptBlocks', padding, 45);

  ctx.fillStyle = mutedColor;
  ctx.font = '12px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  var date = new Date().toLocaleDateString('zh-CN');
  ctx.fillText(date + ' | ' + (currentMode === 'quick' ? '\\u26A1 Quick Mode' : assembled.length + ' blocks'), padding, 65);

  // Divider
  ctx.strokeStyle = isLight ? '#e0e0e8' : '#2a2a3e';
  ctx.beginPath();
  ctx.moveTo(padding, headerHeight);
  ctx.lineTo(canvas.width - padding, headerHeight);
  ctx.stroke();

  // Content text
  ctx.fillStyle = fg;
  ctx.font = fontSize + 'px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  var y = headerHeight + 30;
  lines.forEach(function(line) {
    if (line.trim() !== '') {
      ctx.fillText(line, padding, y);
    }
    y += lineHeight;
  });

  // Footer
  ctx.fillStyle = mutedColor;
  ctx.font = '11px -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  ctx.fillText('Generated by PromptBlocks | wyjing333-dev.github.io/promptblocks', padding, totalHeight - 20);

  // Download
  var link = document.createElement('a');
  link.download = 'promptblocks-' + Date.now() + '.png';
  link.href = canvas.toDataURL('image/png');
  link.click();
  showToast('图片已导出！');
}

// ===== P2-3: AI Model Test Panel =====
function toggleTestPanel() {
  var panel = document.getElementById('testPanel');
  if (!panel) return;
  var cur = panel.style.display;
  panel.style.display = cur === 'none' ? 'flex' : 'none';
}

function runAITest() {
  var text = document.getElementById('promptPreview').textContent;
  if (!text || text.trim() === '') { showToast('拼装区为空'); return; }

  var apiKey = document.getElementById('apiKeyInput').value.trim();
  var model = document.getElementById('modelSelect').value;
  var userInput = document.getElementById('userTestInput').value.trim();
  var resultEl = document.getElementById('testResult');

  if (!apiKey) { showToast('请输入API Key'); return; }
  if (!userInput) { showToast('请输入测试问题'); return; }

  resultEl.innerHTML = '<div style="text-align:center;padding:20px;color:var(--text-muted)">\\u23F3 正在调用AI模型...</div>';

  // Build messages
  var messages = [
    { role: 'system', content: text },
    { role: 'user', content: userInput }
  ];

  // Call API
  var endpoint = '';
  if (model.startsWith('step')) {
    endpoint = 'https://api.stepfun.com/v1/chat/completions';
  } else {
    endpoint = 'https://api.openai.com/v1/chat/completions';
  }

  var body = JSON.stringify({
    model: model,
    messages: messages,
    max_tokens: 1000,
    temperature: 0.7
  });

  fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ' + apiKey
    },
    body: body
  })
  .then(function(res) { return res.json(); })
  .then(function(data) {
    if (data.error) {
      resultEl.innerHTML = '<div style="color:var(--warn);padding:12px;font-size:13px">\\u274C ' + escapeHtml(data.error.message || JSON.stringify(data.error)) + '</div>';
      return;
    }
    var reply = data.choices && data.choices[0] && data.choices[0].message ? data.choices[0].message.content : 'No response';
    resultEl.innerHTML = '<div style="padding:12px;font-size:13px;line-height:1.7;color:var(--text-main);white-space:pre-wrap;border:1px solid var(--border);border-radius:8px;background:var(--bg-hover)">' + escapeHtml(reply) + '</div>';
  })
  .catch(function(err) {
    resultEl.innerHTML = '<div style="color:var(--warn);padding:12px;font-size:13px">\\u274C 网络错误: ' + escapeHtml(err.message) + '<br><br>\\u{1F4A1} 可能原因:\\u003Cbr>1. API Key 无效\\u003Cbr>2. CORS 被拦截（浏览器跨域限制）\\u003Cbr>3. 网络连接问题</div>';
  });
}

function saveAPIKey() {
  var key = document.getElementById('apiKeyInput').value.trim();
  if (key) {
    localStorage.setItem('pb_api_key', key);
    showToast('API Key 已保存（仅本地存储）');
  }
}

// Load saved API key
(function() {
  var saved = localStorage.getItem('pb_api_key');
  if (saved) {
    var input = document.getElementById('apiKeyInput');
    if (input) input.value = saved;
  }
})();

'''

# Find last </script> and insert before it
last_script_idx = content.rfind('</script>')
if last_script_idx != -1:
    content = content[:last_script_idx] + p2_js + '\n' + content[last_script_idx:]
    changes += 1
    print('1c. P2 JS (export + test) inserted')
else:
    print('1c. </script> not found')

# 1d. Add test panel HTML (before history panel)
test_panel_html = '''
<!-- AI Test Panel -->
<div id="testPanel" style="display:none;position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);width:560px;max-width:90vw;max-height:80vh;overflow-y:auto;background:var(--bg-card);border:1px solid var(--border);border-radius:16px;padding:24px;z-index:10001;box-shadow:0 8px 32px rgba(0,0,0,0.4)">
  <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px">
    <h3 style="font-size:16px;color:var(--text-main)">🧪 <span data-i18n="testTitle">测试Prompt效果</span></h3>
    <button onclick="toggleTestPanel()" style="background:none;border:none;color:var(--text-muted);font-size:18px;cursor:pointer">✕</button>
  </div>
  <div style="margin-bottom:12px">
    <label style="font-size:12px;color:var(--text-muted);display:block;margin-bottom:4px">API Key</label>
    <div style="display:flex;gap:8px">
      <input type="password" id="apiKeyInput" placeholder="sk-..." style="flex:1;padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg-main);color:var(--text-main);font-size:13px">
      <button onclick="saveAPIKey()" style="padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg-hover);color:var(--text-main);font-size:12px;cursor:pointer;white-space:nowrap">保存</button>
    </div>
    <div style="font-size:11px;color:var(--text-muted);margin-top:4px">仅存储在本地localStorage，不会上传</div>
  </div>
  <div style="margin-bottom:12px">
    <label style="font-size:12px;color:var(--text-muted);display:block;margin-bottom:4px">模型</label>
    <select id="modelSelect" style="width:100%;padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg-main);color:var(--text-main);font-size:13px">
      <option value="step-3.5-flash">阶跃星辰 Step 3.5 Flash (¥1.35/百万token)</option>
      <option value="step-3-flash">阶跃星辰 Step 3 Flash</option>
      <option value="gpt-4o-mini">OpenAI GPT-4o mini</option>
      <option value="gpt-4o">OpenAI GPT-4o</option>
    </select>
  </div>
  <div style="margin-bottom:12px">
    <label style="font-size:12px;color:var(--text-muted);display:block;margin-bottom:4px">测试问题（用户输入）</label>
    <textarea id="userTestInput" placeholder="输入测试问题，比如"请帮我写一段产品介绍"" style="width:100%;height:60px;padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg-main);color:var(--text-main);font-size:13px;resize:vertical"></textarea>
  </div>
  <button onclick="runAITest()" style="width:100%;padding:10px;border:none;border-radius:8px;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;font-size:14px;font-weight:600;cursor:pointer;margin-bottom:12px">▶ 运行测试</button>
  <div id="testResult" style="min-height:40px"></div>
</div>

'''

# Insert test panel before history panel
history_panel_marker = '<!-- History Panel -->'
if history_panel_marker in content:
    content = content.replace(history_panel_marker, test_panel_html + history_panel_marker, 1)
    changes += 1
    print('1d. Test panel HTML added')
else:
    print('1d. history panel marker not found')

# Add i18n keys for test
content = content.replace("exportImg: '导出图片', testAI: '测试效果',", "exportImg: '导出图片', testAI: '测试效果', testTitle: '测试Prompt效果',", 1)
content = content.replace("exportImg: 'Export Image', testAI: 'Test AI',", "exportImg: 'Export Image', testAI: 'Test AI', testTitle: 'Test Prompt Effect',", 1)
changes += 2
print('1e. Test i18n keys added')

with open(r'D:\jieyuexingchen\promptblocks\index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\nTotal changes: {changes}')
